name: g-mic
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

confinement: devmode # use 'strict' once you have the right plugs and slots

slots:
  plugin:
    interface: content
    content: gimp-plugin
    read:
    - $SNAP/usr/lib/g-mic/gimp

parts:
  g-mic:
    plugin: cmake
    source: https://gmic.eu/files/source/gmic_source.tar.gz
    configflags:
    - -DCMAKE_BUILD_TYPE=Release
    - -DCMAKE_INSTALL_PREFIX=/usr
    - -DBUILD_PLUGIN=ON
    - -DENABLE_DYNAMIC_LINKING=ON
    build-packages:
    - libfftw3-dev
    - libgcc-5-dev
    - libopencv-dev
    - zlib1g-dev
    stage-packages:
    - libfftw3-single3
    - libfftw3-double3
    - libfftw3-quad3
    - libfftw3-long3
    - libgomp1
    - libopencv-core2.4v5
    - zlib1g